### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by shukriadams** [Sitecore/jss#1]
I think you might be missing some stuff from the current version of the quickstart guide at 

    https://jss.sitecore.net/#/setup/quick-start-dev

It looks like this needs node 8.x, and only builds with yarn. I'm running vagrant/ubuntu 16.04 on win10, I don't know if that's imposing additional limitations on my runtime. All attempts to build this with node 7 or with vanilla npm gave a mess of errors.

It also looks like you'r missing some global dependencies that are not described in your setup
- cross-env needs to be installed globally
- scjss-setup - this looks like another expected global dependency, where do we get this?
- scjss-verify-setup - same as above

Also, where is the source code of all the sitecore packages that listed in package.json? They all point back to this project via npmjs.org, but this project is a demo, not a self-contained npm module.

**Comment by sitecorian** [comment]
Hello,

I don't have Ubuntu on win10, handy, so I will try to set it up to repro, but it does work for me on a clean Windows 10 machine with node v6.11.5 and `npm install` / `npm run dev` works as described.

While I am setting up Ubuntu and since you are already on Windows 10, could you please try it "natively" without Ubuntu in the picture? If you see any errors during `npm install`, please paste them here.

Also, what node  and npm version are you on?

**Comment by sitecorian** [comment]
Just tried on Ubuntu 16 / Win 10 with node 6.11.2 / npm 3.10.10 and the basic app setup works fine without yarn.
Could you please paste any errors you are seeing, so we can troubleshoot further.

Regarding the sources for sitecore-jss packages, those are not open source at the moment. Only the samples are.

**Comment by sitecorian** [comment]
Closing as no repro. Please feel free to reopen and provide more details.
