### ISSUE TITLE
Vercel build error for Next JS Sitecore JSS starter code package version

### ISSUE THREAD

**Issue by SairajPrince** [Sitecore/jss#1156]
Can you please specify the correct versions of react, react-dom and types/react, types/react-dom to be used in NextJs sitecore JSS project, we are facing issues currently with Vercel build.
![image](https://user-images.githubusercontent.com/7039898/190364726-9a9c3f94-38ef-4097-98a5-de205cc93f5c.png)

**Comment by illiakovalenko** [comment]
@SairajPrince Thank you for the registered issue
It happens because there are new changes in `next@12.3.0`
We fixed that in #1154, you can look at our solution
In general, you should use our [peerDependencies](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-nextjs/package.json#L67-L71) list
