### ISSUE TITLE
Experience Editor hydration prop mismatch warning

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#1487]
### Describe the Bug

The following warning is shown in the browser console in the Experience Editor:

> Warning: Prop `phkey` did not match. Server: "null" Client: "jss-main"
> code
> PlaceholderComponent@webpack-internal:///./node_modules/@sitecore-jss/sitecore-jss-react/dist/esm/components/Placeholder.js:24:9
> WithComponentFactory@webpack-internal:///./node_modules/@sitecore-jss/sitecore-jss-react/dist/esm/enhancers/withComponentFactory.js:20:74
> Placeholder@webpack-internal:///./node_modules/@sitecore-jss/sitecore-jss-nextjs/dist/esm/components/Placeholder.js:13:84
> div
> Layout@webpack-internal:///./src/Layout.tsx:26:20
> SitecoreContext@webpack-internal:///./node_modules/@sitecore-jss/sitecore-jss-react/dist/esm/components/SitecoreContext.js:21:9
> ComponentPropsContext@webpack-internal:///./node_modules/@sitecore-jss/sitecore-jss-nextjs/dist/esm/components/ComponentPropsContext.js:27:31
> SitecorePage@webpack-internal:///./src/pages/[[...path]].tsx:28:18
> I18nProvider@webpack-internal:///./node_modules/next-localization/dist/index.modern.js:96:18
> App@webpack-internal:///./src/pages/_app.tsx:52:19
> _PathnameContextProviderAdapter@webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:118:18
> ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:305:63
> ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:854:908
> Container@webpack-internal:///./node_modules/next/dist/client/index.js:149:20
> AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:342:18
> Root@webpack-internal:///./node_modules/next/dist/client/index.js:561:19 
> 
> See more info here: https://nextjs.org/docs/messages/react-hydration-error

### To Reproduce

1. Install a new instance of Sitecore 10.3 (XP) in IIS.
2. Create a new JSS Next.js application.
3. Import JSS Styleguide into Sitecore 10.3 instance.
4. Open Experience Editor.
5. Open console and observe error.

### Expected Behavior

No hydration warnings are thrown in the Experience Editor with a fresh install.

### Provide environment information

* Sitecore Version: 10.3 with Sitecore Headless Services Server XP 21.0.587
* JSS Version: 21.1.5
* Browser Name and version: Firefox, 113.0.1
* Operating System and version (desktop or mobile): Windows 11
* Link to your project (if available):

**Comment by ambrauer** [comment]
Hi @coreyasmith - 

This is a [known issue](https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB0545609#:~:text=When%20you%20open%20a%20Next.js%2Dbased%20JSS%20application%20in%20the%20Experience%20Editor%2C%20you%20might%20see%20a%20Warning%3A%20Prop%20%22phkey%22%20did%20not%20match%20error.%20This%20error%20does%20not%20affect%20content%20editing%20and%20you%20can%20ignore%20it%20(463325).) since Sitecore JSS Next.js SDK was introduced (v16). We have it in our backlog to revisit in the near-term; however, it has been a low priority as it does not impact content editing (and it only occurs for next:dev, not production). 

Please feel free to re-open if this is impacting the actual content editing.
