### ISSUE TITLE
Code Splitting and Experience Editor issue

### ISSUE THREAD

**Issue by TheFlyingCodeChimp** [Sitecore/jss#167]
## Description
I'm running code splitting in the method provided by Kam:

https://kamsar.net/index.php/2018/08/Code-splitting-with-Sitecore-JSS-React/

This results in "HTML not found" error in Experience editor when trying to add components. Any components already in the presentation on load are rendered fine.

## Expected behavior
The expected behavior is, on addition of the component to a placeholder, the page reloads with it on the page.

I am pretty sure I understand why this is happening, so I guess the question is more around the best practice for running SSR/Code splitting and also allowing Experience editor functionality?

Unless I don't understand and it should be working fine 👎

**Comment by kamsar** [comment]
It sounds like the Step 3 part may not have been done from my post, which makes the loadable code compatible with SSR (or else something has since changed that invalidates those instructions).

When you add a component, Sitecore re-renders the page in the background to extract the component markup from it to inject into the current page. If the SSR is not working correctly, that rerender will not contain the component markup and you get the missing HTML error.

So check that SSR is working, essentially.

**Comment by TheFlyingCodeChimp** [comment]
Closing as the SSR and Code Splitting wasn't the cause... apologies for the incorrect ticket kam!

Opening discussion about the actual cause in the slack channel to get confirmation before raising a ticket
