### ISSUE TITLE
mediaApi.updateImageUrl loses revision querystring 

### ISSUE THREAD

**Issue by jeppeskovsen** [Sitecore/jss#172]
## Description
When we use `mediaApi.updateImageUrl` function to set sizes, it loses the `rev` querystring.

## Expected behavior
It should keep the `rev` querystring to properly invalidate CDN cache when updated.

**Comment by paulmains** [comment]
I've just discovered this issue. As a workaround i'm currently overriding the mediaApi to accommodate the revision querystring. It would be be great if this one could be remedied.

**Comment by sc-dawidrutkowski** [comment]
Fixed in #275

**Comment by ssartell** [comment]
I think the fix for this issue is causing me issues now. I want to pass the original src for the image and sizing params to get a new src, but the original src is includes w, h, iar, and hash by default from Sitecore (w and h are set to the original size of the image). I can't clear them off without manipulating the src before passing it in. The original implementation of this method would be correct for me.
