### ISSUE TITLE
Vue.js placeholder

### ISSUE THREAD

**Issue by npoliquin** [Sitecore/jss#313]
## Description
It is possible to add a placeholder in the head tag?

## Expected behavior
Add `<placeholder name="jss-head" :rendering="route" />` in the `<head></head>` tag

## Your Environment
* Sitecore Version: N/A Deconnected Mode
* JSS Version: 13.0.0
* Operating System and version (desktop or mobile): Desktop
* Framework: Vue.js

**Comment by kamsar** [comment]
Placeholders must be added to visible locations only since they render visual editing areas. The head tag, being non-visible page metadata, cannot host a placeholder.

To add head data consider adding route level fields for the head data, then reading them off the route when present.

**Comment by sc-illiakovalenko** [comment]
@npoliquin Seems that you get answer. Feel free to open issue if you will have another questions

**Comment by Antonytm** [comment]
I have a similar issue with Next.js. When I put `Placeholder` into `<Head>`, I get everything broken. As far as I understand, `Placeholder` was never intended to work in `<Head>`.

My scenario:
1. We need to have the ability to place scripts into `<head>`. E.g. Google Tag Manager and other tracking scripts
2. We added a placeholder in `<Head>`.
**Expected behavior:** We should be able to render raw HTML. In our case, it is a `<script>` tag with some content inside.
**Actual behavior:** Everything placed in that placeholder remains inside `<body>`. Furthermore, if we have anything under that placeholder, that should go to `<head>`, it also remains in `<body>`.

As far as I understand, it was never intended that a placeholder should work inside the head. But what are the technical limitations, and why it is not possible?
