### ISSUE TITLE
In page editing for Droptree Link field in Sitecore JSS

### ISSUE THREAD

**Issue by spal870** [Sitecore/jss#415]
## Description
We are using JSS headless framework, and if we see the Datatype components available in the Sitecore-JSS-react code base, we see the following items as in the attachment pic. This list is missing component type that we can use for Droptree type field and other reference type fields like Treelist, Multi list etc.

Can you tell us which component type in the sitecore react code will help us make the JSS rendering component editable for a Droptree type field.

## Expected behavior
We want to enable in-page editing for Droptree  field type

## Steps To Reproduce

1. Add droptree fields in any page and load that page in experience editor . Try to edit inline.

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 13.0.5
* Browser Name and version: Chrome 83
* Operating System and version (desktop or mobile): Windows desktop
* Link to your project (if available):

## Screenshots
![image](https://user-images.githubusercontent.com/20183669/87783918-03370680-c853-11ea-89cb-6c692f112962.png)

**Comment by sc-illiakovalenko** [comment]
@spal870 You can look at example, in `styleguide` page

![image](https://user-images.githubusercontent.com/55081915/88031966-fdd50700-cb45-11ea-82d5-e0d55e4a00c5.png)

![image](https://user-images.githubusercontent.com/55081915/88032034-134a3100-cb46-11ea-88bb-7b3686000de4.png)

If you noticed, here is a message:
```
Note: Sitecore does not support inline editing of Item Link fields. The value must be edited in Experience Editor by using the edit rendering fields button (looks like a pencil) with the whole component selected.
```

Basically you can use `<Text />` component for Droptree

**Comment by nickwesselman** [comment]
Hi @spal870, to clarify --

* The Sitecore Experience Editor only supports in-page (inline) editing of a limited number of fields. These are the field for which JSS provides components.
* Internal link fields, such as Droptree, need to be edited in one of the form-based UIs, like the field editor "pencil" button mentioned in the styleguide. To change the Droptree (or Treelist, or Multilist, etc.) field itself and change the linked items, you can use that field editor button.
* As demonstrated in the styleguide and mentioned by @sc-illiakovalenko above, you can still use `<Text />` and other components to render content from the linked item. That can still be edited inline.

Hope this helps. I am going to close this issue since things are working as expected.
