### ISSUE TITLE
[Question] How to control layoutServiceHost value during build? 

### ISSUE THREAD

**Issue by mitikov** [Sitecore/jss#416]
We have a necessity to define different `layoutServiceHost` based on environment/build context for [headless SSR](https://jss.sitecore.com/docs/techniques/ssr/headless-mode-ssr).

The [community approach is to perform token replacement](https://blog.vitaliitylyk.com/devops-with-sitecore-jss-configuration-management/), which smells a bit hacky.

The alternative is to maintain a list of configs, and place proper one based on build context, looks as a variation of previous hack.

@anastasiya29 Could you please suggest an approach/direction to take?

Thanks.

**Comment by sc-illiakovalenko** [comment]
@mitikov You can try this approach:

1. `npm i dotenv`
https://www.npmjs.com/package/dotenv

2.  Create `.env` file, and add required env variables, for example:
`LAYOUT_SERVICE_HOST=https://super_hero.host.com`

3. Edit `scripts/bootstrap.js`:
```js
const configGenerator = require('./generate-config');
const scjssconfig = require('../scjssconfig.json');

require('dotenv').config();

/*
  BOOTSTRAPPING
  The bootstrap process runs before build, and generates JS that needs to be
  included into the build - specifically, the component name to component mapping,
  and the global config module.
*/

const disconnected = process.argv.some((arg) => arg === '--disconnected');

/*
  CONFIG GENERATION
  Generates the /src/temp/config.js file which contains runtime configuration
  that the app can import and use.
*/
const port = process.env.PORT || 3000;
const configOverride = disconnected 
  ? { sitecoreApiHost: `http://localhost:${port}` }
  : {
      sitecoreApiHost: process.env.LAYOUT_SERVICE_HOST || scjssconfig.sitecore.layoutServiceHost
    };

configGenerator(configOverride);

/*
  COMPONENT FACTORY GENERATION
*/
require('./generate-component-factory');
```
We initialized `dotenv` in order to read env variables from `.env` file.
And we can override part of config, where we will take env var LAYOUT_SERVICE_HOST or value from `scjssconfig.json`
```
{
    sitecoreApiHost: process.env.LAYOUT_SERVICE_HOST || scjssconfig.sitecore.layoutServiceHost
};
```
`configGenerator` function responsible for creation of config file: `src/temp/config.js`. All references of `sitecoreApiHost` are linked to `src/temp/config.js`

4. Let's run `jss build` and check `src/temp/config.js` file:
```json
/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.
module.exports = {
  "sitecoreApiKey": "5BABD942-ED4F-475E-90CE-787E3D5A4E42",
  "sitecoreApiHost": "https://super_hero.host.com",
  "jssAppName": "JssReactWeb",
  "defaultLanguage": "en",
  "graphQLEndpointPath": "/api/jssreactweb",
  "graphQLEndpoint": "https://super_hero.host.com/api/jssreactweb?sc_apikey=5BABD942-ED4F-475E-90CE-787E3D5A4E42"
};
```

@mitikov What do you think, does this solution fit for you?
@anastasiya29

**Comment by mitikov** [comment]
Thanks!
