### ISSUE TITLE
Guides RFC - #3 Multisite Scenarios

### ISSUE THREAD

**Issue by anastasiya29** [Sitecore/jss#434]
### RFC background
We have published the 1st version of [JSS Guides & Recommended Practices](https://jss-docs-preview3.herokuapp.com/guides/). This content will ultimately be merged into the JSS Documentation site, and we'd love for the community to be a part of this milestone. We welcome your feedback, questions, change suggestions, and additional content.

### Category - Multisite Scenarios
We’ve create GitHub issues for the 7 topic categories to facilitate group discussion - this issue is for discussing the **`Multisite Scenarios`** category.

Topics in this category:

- [Content Patterns](https://jss-docs-preview3.herokuapp.com/guides/multisite/content-patterns/)
- [Implementation Patterns](https://jss-docs-preview3.herokuapp.com/guides/multisite/implementation-patterns/)
- [Supporting Multiple Languages](https://jss-docs-preview3.herokuapp.com/guides/multisite/multi-language-support/)
- [SXA Integration Guide](https://jss-docs-preview3.herokuapp.com/guides/multisite/sxa-integration/)

### How to contribute

- Post your comments here, or
- [Use this link](https://github.com/Sitecore/jss/pull/431/files?file-filters%5B%5D=.md&w=1) to leave inline comments in the markdown files, or
- Use the `Edit this on GitHub` link at the bottom of each guide page to submit edits for specific pages, or
- Submit pull requests to the [`guides` branch](https://github.com/Sitecore/jss/tree/guides)

---

[:arrow_left: Go to previous category](https://github.com/Sitecore/jss/issues/433) -----  [Go to next category :arrow_right:](https://github.com/Sitecore/jss/issues/435)

**Comment by nickwesselman** [comment]
Some thoughts:

- Nothing here on use of a single app/bundle for multiple sites, which we get asked about and some have implemented. Is there any community content on this? Or should we just discourage?
- Content patterns and discussion of shared content was confusing to me, because it seems to be more about shared design elements.
- That said, should we point people to Helix guidelines w/r/t how to structure your templates and renderings to be shared between sites, particularly if not using SXA?
- `Microsites under the same domain` is confusing to me, not sure what this use case is... does it mean the same domain for the Layout Service call? In that case it's not just about *Micro* sites right?

**Comment by 8or15** [comment]
`The challenge is that from the code side, each app only sees it’s own code, so achieving actual sharing capabilities requires some customization.`

The fact that applications only can reuse their own code is quite a difference comming from the traditional .NET development with Sitecore (not headless). Although this is mentioned it would be great to put more emphasis on this, as it requires a slightly different thinking for the Sitecore veterans.
