### ISSUE TITLE
Next.js sample scaffolded components are not formatted correctly for eslint

### ISSUE THREAD

**Issue by jflheureux** [Sitecore/jss#625]
## Description
For each line of the newly scaffolded component tsx file, there is an `Insert "␍" eslint(prettier/prettier)` error.

Additionally, there is a missing semicolon on line 14 of `component-src.ts`.

## Expected behavior
No eslint errors on newly scaffolded components.

## Steps To Reproduce
1. Start with the Next.js sample app.
2. Scaffold a component using `jss scaffold MyComponent`
3. Open the `components/Component.tsx` file.
4. See error the line ending eslint errors.

## Possible Fix
In `scaffold-component.ts`:
Change
`fs.writeFileSync(outputFile, fileContent, 'utf8');`
To:
`fs.writeFileSync(outputFile, fileContent.replace(/\n/g, '\r\n'), 'utf8');`

## Your Environment
* Sitecore Version: 10.1
* JSS Version: 16.0
* Text Editor: Visual Studio Code
* Operating System and version (desktop or mobile): Windows 10 (1909)

**Comment by justinlaster** [comment]
This issue also presents itself when following the [JSS Quickstart guide](https://jss.sitecore.com/docs/client-frameworks/getting-started/quick-start ) and creating a vanilla react application. The line endings in the scaffolded components are set to `LF` instead of the appropriate `CRLF` endings for Windows. 

While the line endings aren't ideal from an environment perspective, the application does technically work if you silence the error. The error is emitted because the provided `.prettierrc` file has the `endOfLine` setting set to `crlf` (which again, is correct for windows). 

It looks the fix here is to make sure that the `scaffold` command -- and perhaps others -- correctly set line endings based on environment.

**Comment by ambrauer** [comment]
Thanks for reporting @jflheureux and confirming the issue @justinlaster. We've added this to our backlog to resolve in a future release.

**Comment by jrockowitz** [comment]
I am also running into this issue using the JSS Quickstart guide via OSX.  I am very new to Sitecore/JSS but does downgrading JSS fix this issue?

**Comment by jrockowitz** [comment]
Following the guidance from https://tothecore.sk/2021/03/24/creating-version-specific-sitecore-jss-projects/

I was able to downgrade to JSS 15.0.0 using
`jss create my-first-jss-app react -b release/15.0.0`

I think the above fix is also applicable.

**Comment by haramizu** [comment]
Just FYI,

I change .gitattributes parameters 
from
`* text=auto`
to
`* text eol=crlf`
