### ISSUE TITLE
xGraph Browser Grabs Invalid API Key

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#65]
It seems that when you open the xGraph Browser, it grabs the first child under `/sitecore/system/Settings/Services/API Keys` to use as the API key. In my case, I've got my API keys organized in folders under this path, so it's grabbing the ID of a folder, not an API key. I'd expect it to search for a descendant of `/sitecore/system/Settings/Services/API Keys` that inherits from the `API Key` template (`{A6868D65-D612-401F-A40A-CD5BA0857B81}`).

**Comment by kamsar** [comment]
This will be fixed in GM. Note that it will still take the first API-key-looking item descendant, which may not necessarily be valid for the given endpoint. To workaround this, since there's no generic logic to decide on an API key, you can either:

* Create a quiescent API key that is the first one in the API keys folder that is allowed all controllers (one not used by any apps)
* Override the `GraphQL` field type and implement the `GetApiKey()` method to provide your own resolution logic (GM-only)

Additional GM fixes:
* No longer will try to send over-length query strings if the integrated query is too long (will send a comment instead to paste manually)
* Extensible for people with custom requirements by patching virtual methods
