### ISSUE TITLE
"yarn is not supported, please use npm"

### ISSUE THREAD

**Issue by sowhatdoido** [Sitecore/jss#84]
```
"engines": {
    "node": ">=8.1",
    "npm": ">=5.6.0",
    "yarn": "yarn is not supported, please use npm"
  },
```

Is there a reason why yarn isn't supported? I tried looking at past issues but didn't seem to see any discussion as to why yarn would be removed

**Comment by kamsar** [comment]
Issues involving shipping synchronized package lock files, and the near impossibility thereof.

You're welcome to use yarn, if you want to manage the lock files yourself (and any package versions that may slip and break things), but the official sample apps will ship with npm lockfiles.

The driver behind this was that the TP4 Angular apps broke because of a downstream package not using SemVer correctly and installing a newer package version that was for an Angular version we did not yet support. Several people had JSS "break" due to that.

**Comment by sowhatdoido** [comment]
Great! Thanks for the explanation!
